[rooms.main]
before="sleep 5"
runSynchronous="sleep 10"
after="sleep 5"
finally="sleep 5"
path="./main/"

[rooms.secondary]
before="sleep 1"
runSynchronous="sleep 10"
after="sleep 1"
finally="sleep 10"
path="./secondary/"
